# Generated by Django 4.2.11 on 2026-02-12 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gear', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gearreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gearkit',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_kits', to='gear.category'),
        ),
        migrations.AddField(
            model_name='gearimage',
            name='gear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='gear.gearkit'),
        ),
        migrations.AddField(
            model_name='gearavailability',
            name='gear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='gear.gearkit'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='categories_slug_b4303a_idx'),
        ),
        migrations.AddIndex(
            model_name='gearreview',
            index=models.Index(fields=['gear'], name='gear_review_gear_id_ad3d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='gearreview',
            index=models.Index(fields=['rating'], name='gear_review_rating_8ae31e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gearreview',
            unique_together={('gear', 'user')},
        ),
        migrations.AddIndex(
            model_name='gearkit',
            index=models.Index(fields=['slug'], name='gear_kits_slug_deea44_idx'),
        ),
        migrations.AddIndex(
            model_name='gearkit',
            index=models.Index(fields=['category'], name='gear_kits_categor_45c3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='gearkit',
            index=models.Index(fields=['status'], name='gear_kits_status_1dae84_idx'),
        ),
        migrations.AddIndex(
            model_name='gearkit',
            index=models.Index(fields=['is_featured'], name='gear_kits_is_feat_4ccc20_idx'),
        ),
        migrations.AddIndex(
            model_name='gearavailability',
            index=models.Index(fields=['gear', 'date'], name='gear_availa_gear_id_ab2ae8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gearavailability',
            unique_together={('gear', 'date')},
        ),
    ]
